# Generated by Django 3.1 on 2023-06-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldate', models.CharField(max_length=30, verbose_name='时间')),
                ('luser', models.CharField(max_length=20, verbose_name='姓名')),
                ('operate', models.CharField(choices=[('login', '登录'), ('exit', '退出'), ('exam', '考试'), ('score', '查询成绩')], max_length=20, verbose_name='操作')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=4, verbose_name='性别')),
                ('dept', models.CharField(choices=[('计算机科学与工程学院', '计算机科学与工程学院'), ('电气与自动化学院', '电气与自动化学院'), ('外国语学院', '外国语学院'), ('理学院', '理学院')], default='计算机科学与工程学院', max_length=20, verbose_name='学院')),
                ('major', models.CharField(default='软件工程', max_length=20, verbose_name='专业')),
                ('password', models.CharField(default='111', max_length=20, verbose_name='密码')),
                ('email', models.EmailField(default='gpu0@qq.com', max_length=254, verbose_name='邮箱')),
                ('birth', models.DateField(default='2020-01-02', verbose_name='出生日期')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='PaperOver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('sid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': '完成试卷',
                'verbose_name_plural': '完成试卷',
                'db_table': 'paper_over',
            },
        ),
    ]
