# Generated by Django 3.1 on 2023-06-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperover',
            name='data',
            field=models.JSONField(default='json', verbose_name='考试内容'),
        ),
    ]
