# Generated by Django 3.1 on 2023-06-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20230615_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperover',
            name='data',
            field=models.JSONField(default={}, verbose_name='考试内容'),
        ),
    ]
